/**
 * Copyright 2020 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kie.kogito.traffic

unit LicenseValidationService

import java.util.*


rule "Is driver license valid"
when            
    $driver: /driver[licenseExpiration.after(currentTime)]
    NameQuery($driver,$nam;)
then
    System.out.println($nam);
    $driver.setValidLicense(true);
end



query NameQuery(Driver $driver, String $nam)
    /driver[
        $nam := name
    ]
end

rule "Is driver license expired"
when            
    $driver: /driver[licenseExpiration.before(currentTime)]
then
    $driver.setValidLicense(false);
end

query "validation"
  $driver : /driver
end